### ISSUE TITLE
Adding DataHUB (federated) test environment as login option to application

### ISSUE THREAD

**Issue by akirbis** [nfdi4plants/arcmanager_frontend#12]
### Goals:

(I)  Adding the DataHUB test environment to the ARCmanager application as login option in the drop-down menu
(II) Backend adjustments to enable user authentication and give users access to the new DataHUB

### Preparations:

The current state of the production server was saved by pushing uncommitted changes to the dev branch (frontend repo was already up-to-date). For all subsequent changes, I created separate branches for both [frontend](https://github.com/nfdi4plants/arcmanager_frontend/tree/dataplant_testenv_integration) and [backend](https://github.com/nfdi4plants/arcmanager_backend/tree/dataplant_testenv_integration) repository (dataplant_testenv_integration).

### Modifications made:

The exact changes can be retraced by comparing the dev branch with the new feature branch for each repository:

backend repo: https://github.com/nfdi4plants/arcmanager_backend/compare/dev...dataplant_testenv_integration
frontend repo: https://github.com/nfdi4plants/arcmanager_frontend/compare/dev...dataplant_testenv_integration

In addition, I added the ARCmanager as a new application to the DataHUB test environment Gitlab and stored the application ID and secret in the corresponding file on the production server.

### Preliminary changes to production server:

Re-building the frontend application with the new changes failed at first because of outdated/missing dependencies, so I updated all packages (`npm install`). After re-building the frontend application (`npm run build`), an empty white page was served under the ARCmanager URL. Some troubleshooting revealed that the URLs were not properly resolved. To fix that, I added the base path '/arcmanager/app/' to the _vite.config.ts_ file. Afterwards, the application was accessible again under the normal URL and everything worked as expected.

### To do:

Please briefly review the changes on the production server to make sure I didn't mess up anything unintentionally. If everything is okay the feature branch can be merged into one of the production branches. The frontend and backend repo on the production server are currently on the dataplant_testenv_integration branches, don't forget to set them back to dev or main when the feature branch is merged.

**Comment by Lu98Be** [comment]
Looks good. I merged the branches 👍
