### ISSUE TITLE
Bug:  unintended behaviour when adding units to building blocks

### ISSUE THREAD

**Issue by akirbis** [nfdi4plants/arcmanager_frontend#8]
## Current situation

While adding a unit to a newly created building block, when searching for a unit term after choosing a term for the building block, the `Search building block` search bar is used again, instead of the `Search building block unit`. When the unit term is typed inside the `Search building block` field as well, everything works as intended. Screenshots for clarification (both show results after clicking `SEARCH UNIT` button)

<img width="728" alt="2024-07-25_ARCmanager_unit_column_bug_1" src="https://github.com/user-attachments/assets/bb111a1a-4688-40a2-9648-85cb40a76bf9">

<img width="664" alt="2024-07-25_ARCmanager_unit_column_bug_2" src="https://github.com/user-attachments/assets/dbd46e33-a310-4e56-bb86-750dda1aecee">

## Intended behaviour

Only `Search building block unit` search field is used for looking up unit terms when adding a unit to a building block.

**Comment by Lu98Be** [comment]
Found the bug and fixed it for the next version.

**Comment by Lu98Be** [comment]
fixed in new version 0.9.2

**Comment by Lu98Be** [comment]
fixed in new version 0.9.2
