### ISSUE TITLE
Feature request: option to rearrange annotation table columns

### ISSUE THREAD

**Issue by akirbis** [nfdi4plants/arcmanager_frontend#9]
## Requested new feature

I don't know how hard this is to implement, but it would be nice to be able to rearrange the order of columns in annotation tables. This could be done either via drag-and-drop, or alternatively with arrow-symbols next to each column (move left, move right).

## Potential problems

- helper columns with ontology terms etc. have to move together with their main column
- Input and Output columns should be fixed at the first/last position without the possibility to move them around

**Comment by Lu98Be** [comment]
I decided to add a new row of buttons to navigate the columns (drag and drop is too much of a hassle to implement)

With them you can shift a column left or right and align them in the sheet as you want.

Here is a screemnshot of the new buttons in general:

![terms hidden](https://github.com/user-attachments/assets/5c9bfb03-0744-472f-913d-e428bf600a3a)

To somehow "demonstrate" the shift I made two screenshots.

Before:

![before shift](https://github.com/user-attachments/assets/b206d5d5-87fe-45ea-852b-807ece2ba80b)

After:

![after shift](https://github.com/user-attachments/assets/c669af99-78fd-4878-863d-c4cbe0b0a3ca)

But the best way to test this, is to try for yourself.
I will add the changes now and push it to the live version.

**Comment by Lu98Be** [comment]
added new arrow buttons to shift columns to left and right in new version 0.9.2
